### ISSUE TITLE
How to export OCTA data as .OCT file

### ISSUE THREAD

**Issue by AlanZhang1995** [camlloyd/oct-to-tiff#17]
Hi Cameron Lloyd,

Thanks a lot for your work! This repo is really helpful.
But I am not sure how to export the OCTA data using Optovue software, whose name is "ReVue" I guess. In detail, I can export a .OCT file and even there is a string "Angio Retina" in its name, the content after I read it using your package is only OCT images. I do not think this is a problem about your repo, but the file does not contain OCTA data at all.
What about your OCTA data? or do you have any idea about exporting OCTA data?
Looking forward to your reply!

**Comment by camlloyd** [comment]
Hi @AlanZhang1995,

Congratulations, you have opened the first issue! It is great to hear you have managed to convert your OCT data. 
How did you find installing and using oct-to-tiff? Any feedback is much appreciated (example data is even better).

Correct, the `.OCT` files only contain structural OCT data. For OCTA data:

- Go to _File > Data Transfer > Output Data_. This should create at least two new folders.

- OCTA data is stored in these folders as `.images` files. To find the Angio Retina scans:

```
$ grep -lr 'ScanPatternName="Angio Retina"' /DiagnosisData/
```

- This data is compressed. To extract the raw data, I recommend [binwalk](https://github.com/ReFirmLabs/binwalk):

```
$ binwalk -e /DiagnosisData/.images
```

- This should create a new file without an extension. Now you can try again using:

```
$ oct-to-tiff /path/to/new/file --angio --size 4.5
```

- See [Optional arguments](https://github.com/camlloyd/oct-to-tiff#optional-arguments) in the README for more info.

Conversion of OCTA data is still an experimental feature. Now there is interest, I will try to prioritise it for `v0.3.0`. 
However, it is unlikely this will be before next month.

Good luck!

**Comment by AlanZhang1995** [comment]
Hi camlloyd,

Thanks for your warm reply and sorry for reply later. It took me some time to apply for the accesss of our database.

For the feedback, 
I found this wonderful repo by searching on github. My work requires me to find a way to export raw data from Optovue machine but I have no idea about this. So I searched relative repos on github using kerword "OCTA"+"Optovue" and skim the results one by one. One sentence in your repo catched my eyes which said "This tool has been developed by reverse engineering data from the Optovue RTVue XR Avanti System." and I though this one had higher possible to be helpful. Besides, I know you before in a repo named "OCT-convert". So I think you may be an experent in this filed and decide to give it a try. Thanks for your hard work! However, I apologize that I am not allowed to share the data. 

For my problem, 
I did _File > Data Transfer > Output Data_ but no `.images` files are found.
There are indeed two folders and some files without extensions. But I still do not know how to use them.
The whole data structure looks like this:
.
├── DiagnosisData
│   ├── 28
│   │   └── 281278aeef9f2d49b7b4c7801e526e80
│   ├── 29
│   │   └── 2995731547a13547bec38a8a30cf1c00
│   ├── 43
│   │   └── 438187cbf2adcf409c69a91b211a0f6d
│   ├── 63
│   │   └── 63e28a8e05001c44a0ead2cd56d413f1
│   ├── 65
│   │   └── 659cb1b4b05ef24bb78049da79a41f42
│   ├── 84
│   │   └── 846f96adb65afa46a633fcb1bd1a9c46
│   ├── 93
│   │   └── 938694bbd5f4ac48a649782d2879618f
│   ├── 95
│   │   └── 957ce7d69c757c4984c7f310f226facc
│   ├── 98
│   │   └── 985e8a8835b9f4498e323cbad54e617b
│   ├── ab
│   │   └── ab832a35173a6147947d54d7a4dd1100
│   ├── df
│   │   └── df534d28a2d1b948a892f807af9247f0
│   └── f8
│       └── f8efa97876eddf4b957d08abf3dfd062
├── OutputDB.bak
└── RawData
    ├── 28
    │   └── 281278aeef9f2d49b7b4c7801e526e80
    ├── 29
    │   └── 2995731547a13547bec38a8a30cf1c00
    ├── 43
    │   └── 438187cbf2adcf409c69a91b211a0f6d
    ├── 63
    │   └── 63e28a8e05001c44a0ead2cd56d413f1
    ├── 65
    │   └── 659cb1b4b05ef24bb78049da79a41f42
    ├── 84
    │   └── 846f96adb65afa46a633fcb1bd1a9c46
    ├── 93
    │   └── 938694bbd5f4ac48a649782d2879618f
    ├── 95
    │   └── 957ce7d69c757c4984c7f310f226facc
    ├── 98
    │   └── 985e8a8835b9f4498e323cbad54e617b
    ├── ab
    │   └── ab832a35173a6147947d54d7a4dd1100
    ├── df
    │   └── df534d28a2d1b948a892f807af9247f0
    └── f8
        └── f8efa97876eddf4b957d08abf3dfd062

Best Regard!

**Comment by camlloyd** [comment]
Thanks for the feedback. 

Under _Help > About RTVue XR..._ 

1. Which software version do you have?
2. Which feature upgrades, if any, do you have?

**Comment by AlanZhang1995** [comment]
It is strange. Maybe we use different software. In my case, the option is about ReVue and its version is 2018.1.1.63. No feature upgrades.

**Comment by AlanZhang1995** [comment]
It works! Wonderful!
The extracted raw data has 29573120 bytes, which means depth = 160 x height = 304 x width =304 x 2 bytes per pixel I suppose. Could we extract the layer segmentation bounderies also?

**Comment by camlloyd** [comment]
> Wait! I do find some .image files this time. Let me try binwalk again. Thanks!

What did you do differently this time?

> It works! Wonderful!
> The extracted raw data has 29573120 bytes, which means depth = 160 x height = 304 x width =304 x 2 bytes per pixel I suppose. Could we extract the layer segmentation bounderies also?

Correct. I am looking into extracting segmentation lines.

**Comment by AlanZhang1995** [comment]
> What did you do differently this time?
Maybe I tried a different patient. lol.
Or maybe someone updates the software when I did not know, since I reported the problem once.
> Correct. I am looking into extracting segmentation lines.
Great! Thanks!

**Comment by AlanZhang1995** [comment]
> Do you plan on exporting another scan? If yes, it would be helpful to know which of these is the cause of the problem.

That's fine. I would like to help! I can try to export that patient again and ask my colleague about the software version. 

By the way, do you have any idea about any python packages which implenment the projection artifacts removal processing? In fact, I am trying to generate 2D projections from 3D volumes myself based on the extracted layer segmentation lines.  However, my current results shows the deep layer projections always have shadows of shallow layer.

**Comment by AlanZhang1995** [comment]
> Do you plan on exporting another scan? If yes, it would be helpful to know which of these is the cause of the problem.

I checked the previous patient and _File > Data Transfer > Output Data_ still works. I suppose some IT guys helped us upgrade the software or add some lisences.

> I do not, no. The 3D PAR algorithm in question is proprietary. If you find an alternative, please do share!

I will do that if I find any. Thanks!
